[에바] - Week3
codeit-bootcamp-frontend/Weekly-Mission pull request #45
Opened 2023-04-09 14:39 UTC by shyjnnn

# Week 3 Mission

## Requirements

### 필수 요구사항

### 전체

- [x]  로고 클릭시 루트 페이지(“/”)로 이동해야 합니다.
- [x]  로그인 페이지, 회원가입 페이지 모두 로고위 상단 여백이 동일해야 합니다.
- [x]  input 요소에 focus in 일 때, input 안에 문자열은 검정색이어야 하고, 파랑색 테두리가 생겨야 합니다.
- [x]  input 요소에 focus out 일 때, input 안에 문자열과 테두리는 회색이어야 합니다.
- [x]  SNS 아이콘들은 클릭 가능함을 확인할 수 있고, 클릭시 각각 “[[https://www.google.com/”](https://www.google.com/%E2%80%9D)](https://www.google.com/%E2%80%9D), “[[https://www.kakaocorp.com/page/”](https://www.kakaocorp.com/page/%E2%80%9D)](https://www.kakaocorp.com/page/%E2%80%9D) 으로 이동합니다.

### 로그인페이지

- [x]  회원 가입하기는 클릭 가능함을 확인할 수 있고, 클릭시 “/signup” 페이지로 이동합니다.
- [x]  이메일 input에서 focus out 일 때, 값이 없을 경우 alert으로 “이메일을 입력해주세요.” 메세지를 보입니다.
- [x]  이메일 input에서 focus out 일 때, 값이 있고, 이메일 형식에 맞지 않을 경우 alert으로 “올바른 이메일 주소가 아닙니다.” 메세지를 보입니다.
- [x]  이메일: [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com), 비밀번호: codeit101 으로 로그인 시도할 경우, “/my-link” 페이지로 이동합니다.
- [x]  이외의 로그인 시도의 경우, “이메일과 비밀번호를 확인해주세요.” 메세지가 담긴 alert 을 띄워 주세요.
로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행돼야 합니다.
- [x]  비밀번호 찾기는 클릭 가능함을 확인할 수 있고, 클릭시 “/forgot-password” 페이지로 이동합니다.

### 회원가입 페이지

- [x]  로그인 하기는 클릭 가능함을 확인할 수 있고, 클릭시 “/signin” 페이지로 이동합니다.
- [x]  이메일 input에서 focus out 일 때, 값이 없을 경우 alert으로 “이메일을 입력해주세요.” 메세지를 보입니다.
- [x]  이메일 input에서 focus out 일 때, 값이 있고, 이메일 형식에 맞지 않을 경우 alert으로 “올바른 이메일 주소가 아닙니다.” 메세지를 보입니다.
- [x]  이메일 input에서 focus out 일 때, input 값이 [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com) 일 경우, alert으로 “이미 사용 중인 아이디입니다.” 메세지를 보입니다.
- [x]  비밀번호 input에서 focus out 일 때, 값이 없거나 문자열만 있거나 숫자만 있는 경우, alert으로 “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 메세지를 보입니다.
- [x]  회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 부분을 alert 메세지로 알립니다.
- [x]  이외의 유효한 회원가입 시도의 경우, “/my-link”로 이동합니다.
- [x]  회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 실행돼야 합니다.

### 모바일 크기

- [x]  375px 보다 작은 크기의 기기는 고려하지 않습니다.
- [x]  좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- [x]  내부 요소들의 너비는 기기의 너비가 커질수록 커지지만 400px을 넘지 않습니다.

### 선택 요구사항

### 전체

- [x]  비밀번호 input 요소에 비밀번호를 확인할 수 있는 아이콘을 추가합니다.
- [x]  비밀번호를 확인할 수 있는 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 합니다.

## Key Changes
1. Week2 Refactoring
    - break 용도(글 줄바꿈)의 span을 br로 변 경 display : none을 사용해 모드에 따라 적용하였습니다.
    - 62.5% Trick을 반영하여 px→ rem으로 변경하였습니다.
    - media query width 범위 지정을 max로 통일하였습니다.
    - 의미있는 class 명으로의 변경과 불필요한 id 지정을 변경하였습니다.
    - header를 absolute후 margin-top이 아닌 sticky로 변경했습니다.
    - article을 flex wrap와 align-content:center 로 정렬하는 것에서 grid로 변경했습니다.
 
2. 폴더 refactoring
    - index.html 방식으로 변경 및 static에 css와 imgs 정리
    ![image](https://user-images.githubusercontent.com/81355590/230777044-6c5f46bb-9492-49cb-bf7d-7368886b30c0.png)

3. `alert` 무한 루프 발생
    - 로그인페이지에서 이메일 형식이 아닌 아이디를 입력 후 Enter를 사용해 submit을 할 경우 `이메일과 비밀번호를 확인해주세요` alert 가 발생한 후 `올바른 이메일 주소가 아닙니다.` alert의 무한 루프에 빠지게 되는 이슈가 발생했습니다.
    - 회원가입 페이지에서 로그인 input에 focus를 둔 후 비밀번호의 input으로 focus를 옮길 경우 focusout에 대한 aler 무한 루프에 빠지는 이슈가 발생했습니다. (반대의 경우도 마찬가지 입니다)
    - 원인은 alert로 인한 focsout이 발생하기 때문이었습니다. 정말 모르겠어서 ChatGPT한테 물어보고..😅 click이나 다른 물리적 focusout event와 alert로 인한 focusout event의 차이가 `sourceCapability`의 차이임을 알게 되었습니다.
        - 이를 사용해서 구현했지만 좋지 않은 코드인 것이 ~~직감적으로~~ 느껴집니다..ㅎㅎ
            - 시간 관계상 아직 못했지만 리팩토링을 하며 앨리스가 공유해준 setTimeOut을 사용한 방법을 시도해볼 예정입니다!

4. focus에 따른 스타일 변경
    - focusin이 되었을 때 테두리 색이 보라색으로 변경되는 것에 대해 css 가상클래스를 사용해 구현했습니다.
    - focusin이 되었을 때 텍스트이 색을 검정색으로 변경되는 것에 대해선  js의 classList에 class를 추가하는 방식으로 구현했습니다.
    
## Results

#### [evalinkbrary](https://evalinkbrary.netlify.app/)👈이곳에서 확인 가능합니다!

<hr>

### Reference

[참고자료](url)

### Questions
모든 질문에 대해 해당 코드 부분에 comment 달았습니다!

- alrticle을 flex에서 grid로 변경 시 생긴 이슈
   ![스크린샷 2023-04-06 153427](https://user-images.githubusercontent.com/81355590/230778710-7fff974f-b897-4e1c-b286-97829717e9c3.png)
    - comment로 코드 부분에 달아두겠습니다!
    
- KeyChanges 3번의 궁금증
    - 무한 alert가 발생하지 않도록 하는 방법을 3일 정도 고민했는데 도저히 떠오르지가 않습니다. 처음엔 alert 발생 시 강제로 focus가 이동할 수 없도록 `요소.focus()`를 주고 eventListener를 제거하는 방식으로 구현했습니다. 그렇게 되면 focusin이 되었을 때 다른 곳을 클릭조차 할 수 없는 문제가 생겼습니다.
    - 따라서 foucsin이 아닌 focusout일때 eventListner를 등록하여 해결했는데, 그 경우 최초 1회에는 validation이 되지 않는 문제가 발생했습니다(최초 1회에는 focusout을 해도 리스너 없는 상태이기 때문)
    - 앨리스가 공유해준 setTimeout 방식을 사용해볼 예정인데 이 방식이 괜찮은 것인지 궁금합니다!(아직은 시간관계상 못했습니다 ㅠㅠ)

- KeyChanges 4번의 focus에 따른 스타일 변경에 대한 궁금증
    - 텍스트이 색을 검정색으로 변경되는 경우에도 css 가상클래스로 구현 가능한 것으로 알고 있습니다.  css와 js 중 어떤 방식이 더 나은지 궁금합니다!
- 링크 이동 (주소 전환)을 할 때 `location.href = "../my-link/";`을 사용하면서 리로드를 막기 위해 `e.preventDefault();`를 해야함을 알았습니다. 비효율적인 것 같은데 링크 이동의 다른 방식이 궁금합니!

2023-04-09 16:06 UTC, shyjnnn reviewed
Q1. article을 flex에서 grid로 변경 시 생긴 이슈 에 대한 comment

2023-04-09 16:06 UTC, shyjnnn commented on static/css/home/style.css
> +  display: grid;
![스크린샷 2023-04-06 153427](https://user-images.githubusercontent.com/81355590/230783351-314205c6-5420-4b1f-a79c-f9c260d1407c.png)
현재 리펙토링을 하면서 사진과 같이 모바일 모드에서 제목(h2), 이미지, 설명(p) 순 배치를 위해 grid로 묶어주었습니다.

그런데 134줄 `grid-template: repeat(2, auto) / repeat(2, auto);` 부분을 개발자모드에서 해제하여도 사진처럼 배치가 되더라구요,  하위요소들을 grid-row : 1/3으로 위치 지정을 사용해서 가능한 걸까요? 추가적으로 👉grid-column을 명시하지 않아도 배치가 되었습니다.

하위요소로는 h2, p, img가 있습니다. comment 달아뒀습니다! 

### 궁금한 점
1. 👉 `grid-template: repeat(2, auto) / repeat(2, auto);`의 `repeat(2, **auto**)` 파트의 문법이 괜찮은 것인지 궁금합니다. 비율을 어떻게 할지 고민하다 계산을 하기 보다는 자동으로 배치되었으면 좋겠다는 생각에 적었는데 작동을 하는 듯 했습니다. 그런데 이렇게 작성한 다른 분들의 코드를 찾지 못했습니다.. 원래 없는 문법일까요..?(강의에서도 없었습니다 ㅎㅎ..)
2. 마찬가지로 `grid-template: repeat(2, auto) / repeat(2, auto);` 이부분을 해제해도 잘 동작합니다. 제 생각에는, 자식 요소들의 grid-row 때문이라고 생각하는데, 그렇다면 보통 grid comtainer에 template을 지정안하는 경우가 있나요? 일반적이지 않은 것 같아 질문드립니다!!
3. 하위요소들에 `grid-row`만 설정하고 👉`grid-column`은 설정하지 않아도 동작을 합니다. 이것 또한 이유를 모르겠습니다😱😱

**결론은 `grid-template: repeat(2, auto) / repeat(2, auto);`와 `grid-column` 없이 하위요소들에 `grid-row`만 설정해도 이 배치가 완성됩니다.. 원래 그런걸까요?**

> 참고로 article 요소에 다른 grid나 flex 등 영향을 주는 건 없습니다!

2023-04-09 16:06 UTC, shyjnnn commented on static/css/home/style.css
> +article h2.left-sort {
하위요소 h2의 grid 설정 입니다. grid-column을 설정해주지 않았습니다.

2023-04-09 16:06 UTC, shyjnnn commented on static/css/home/style.css
> +article p.left-sort {
하위요소  p 의 grid 설정입니다

2023-04-09 16:06 UTC, shyjnnn commented on static/css/home/style.css
> +article .content-imgs.left-sort {
하위요소 img의 grid 설정입니다

2023-04-09 16:18 UTC, shyjnnn reviewed
Q2에 대한 코드 및 Q3.  focus에 따른 스타일 변경에 대한 궁금증 코드

2023-04-09 16:18 UTC, shyjnnn commented on signup/signup.js
> +  if (e.sourceCapabilities === null) {
Q2.에 대한 코드

focusin 이벤트 발생 시 focusout alert에 대한 이벤트리스너를 등록하게 하였고, alert발생으로 인한 focusout과 실제 디바이스(사용자)에 의한 focusout event의 차이점인 `sourceCapabilities 값`의 차이를 이용했습니다. (with ChatGPT..)

이 방식이 보편적이진 않은 것 같습니다(구글링을 해도 X..) 이보다 setTimeOut을 사용해 리스너를 등록, 삭제하는 과정을 거치는 것이 나을까요?

2023-04-09 16:18 UTC, shyjnnn commented on signin/signin.js
> +function focusIn(e) {
Q. focus에 따른 스타일 변경에 대한 궁금증

텍스트이 색을 검정색으로 변경되는 경우에도 css 가상클래스로 구현 가능한 것으로 알고 있습니다.  css와 js 중 어떤 방식이 더 나은지 궁금합니다!

2023-04-09 16:18 UTC, shyjnnn commented on sign/sign.css
> +form input:focus {
테두리 색은 css의 가상클래스를 사용해 focusin 시 보라색으로 테두리색이 바뀌도록 설정했습니다. (commit 메시지가 잘못 된 것 같습니다. 텍스트에 대한 색바뀜은 적용X 뒤에서 js로 적용함)

2023-04-09 16:21 UTC, shyjnnn commented on signup/signup.js
> +    location.href = "../my-link/";
Q4 코드

링크 이동 (주소 전환)을 할 때 location.href = "../my-link/";을 사용하면서 리로드를 막기 위해 e.preventDefault();를 해야함을 알았습니다. 비효율적인 것 같은데 링크 이동의 다른 방식이 궁금합니다!

2023-04-10 08:53 UTC, ghost requested changes

2023-04-11 04:36 UTC, shyjnnn commented on signup/signup.js
> +  if (e.sourceCapabilities === null) {
케니와 확인해본 결과 무한 alert가 맥북에선 발생을 안하는데 window에서만 발생합니다😂

이메일의 input에 focus를 뒀다가 비밀번호의 input을 클릭하게 되면 비밀번호에 대한 alert가 무한으로 발생합니다.
처음에는 코드를 대략적으로 아래와 같이 작성했었는데요,
```jsx
function isValidEmail(){
	// 유효한 이메일에 대한 조건. 만족 X시 alert 발생
}

function isValidPassword(){
	// 유효한 비밀번호에 대한 조건. 만족X 시 alert 발생
}

const email = documnet.querySelector(".email-input")
const password= documnet.querySelector(".password-input")

email.addEventListener("focusout", isValidEmail)
password.addEventListener("focusout", isValidPassword)
```

이렇게 단순하게 코드를 구현했을 때, window에서는 alert가 무한으로 발생합니다. 
이를 해결하기 위해서 removeEventListener를 사용하려하다보니 현재코드의 상태로 변경되었습니다.(불필요한 이벤트핸들러 안에 이벤트헨들로 선언은 고치겠습니다!)

아마도(순서는 추측) email input→ password input 클릭의 예시를 들어보면,
email input에 focus가 되어있는 상태에서 password input을 클릭할 경우 
1. email에 focus가 있는 상태로 password 클릭 (password focusin)
2. email alert 발생 → **focus alert로 이동**
3. 확인버튼 → password focusin
4. 2번의 **focus alert로 이동**에 대한 password focusout alert 발생
5. alert가 발생하면 **focus alert로 이동**
6. 확인 버튼 → password focusin
7. 5번의 **focus alert로 이동**에 대한 password focusout alert 발생
무한 반복

아마도 이런식으로 무한 alert가 발생하는 것 같습니다😂😂

그래서 `sourceCapabilities`나 `setTimeout()` 함수로 강제하려는했는데, 이외의 방법이 모르겠습니다..😂😂😂

2023-04-14 07:10 UTC, shyjnnn commented on static/css/home/style.css
> +  display: grid;
mobile 모드에서 grid로 지정해 gap을 주려고 했던 것인데, 일반 pc모드에서도 중복으로 작성한 것 같습니다. 수정했습니다!

2023-04-14 08:14 UTC, shyjnnn commented on signup/signup.js
> +  if (isValidEmail(e) || isValidPassword(e) || isValidPasswordCheck(e)) {
`||` -> `&&`로 변경했습니다! 잠시 헷갈렸었는데 집어주셔서 감사합니다.

2023-04-14 08:18 UTC, shyjnnn commented on static/css/sign/sign.css
> +}
`position: relative`인 부모태그를 추가해 **input 상자 높이 만큼을 가지게 하고**, `top: 50%` 과 `transform: translateY(-50%);` 으로 세로 가운데 정렬했습니다!

2023-04-14 08:43 UTC, ghost commented on signup/signup.js
> +  if (e.sourceCapabilities === null) {
공유 감사합니다! 일단은 `alert()` 를 사용할 때 크롬의 버그인 거 같습니다!

2023-04-14 08:45 UTC, ghost commented
일단 이번 PR은 머지하도록 하겠습니다!!

2023-04-14 08:45 UTC, merged