[노아] - week3
codeit-bootcamp-frontend/Weekly-Mission pull request #46
Opened 2023-04-09 15:00 UTC by Noahcodeit

### 1주차와 2주차까지밖에 완성을 못했습니다.. 죄송합니다ㅠㅠ 이번주가 week3라 여기에 PR 드립니다. 감사합니다.
# 1). 1주차
## 필수 요구사항

- [x] 최상단에 Linkbrary 아이콘은 클릭 가능함을 알 수 있도록 마우스가 위로 올라갔을 때, 커서가 손가락 모양으로 바뀌어야 하고, 클릭 시 루트 페이지(‘/’)로 이동 합니다.

- [x] ‘로그인’은 클릭 가능함을 알 수 있어야 하고, 클릭 시 로그인 페이지(‘/signin’)로 이동 합니다.

- [x] ‘링크 추가하기’는 클릭 가능함을 알 수 있어야 합니다.
- [x] ‘Privacy Policy’, ‘FAQ’는 클릭 가능함을 알 수 있어야 하고, 클릭 시 각각 개인정보보호 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동 합니다.
- [x] 우측 하단에 페이스북, 트위터, 유튜브, 인스타그램 아이콘은 클릭 가능함을 알 수 있어야 하고, 클릭 시 각각의 홈페이지로 이동 합니다.
- [x] 페이스북, 카카오톡, 슬랙에서 사이트 링크 공유 시 미리보기를 볼 수 있어야 합니다.

## 추가 요구사항
- [ ] 글자와 버튼에 그라데이션을 적용합니다.

- [x] 브라우저 너비가 1920px을 넘어갈 경우 내부 요소들의 위치는 고정되고, 여백만 커지도록 해주세요.

- [x] 트위터에서 사이트 링크 공유 시 아래 두번째 예시와 같은 미리보기를 볼 수 있어야 합니다. (미리보기에 들어갈 내용은 페이스북 등에 공유할 때 설정한 데이터와 동일한 데이터를 보여줘야 합니다.)<br/><br/>

# 2). 2주차 
## 필수 요구사항 
- [x] 반응형 디자인을 적용해 주세요. 
PC: 1200px 이상
tablet: 768px 이상 ~ 1199px 이하
mobile: 375px 이상 ~ 767px 이하
375px 미만 사이즈의 디자인은 고려하지 않음

- [x] 아래로 스크롤 해도  “Linkbrary”와 “로그인" 버튼이 들어있는 gnb 영역이 최상단에 고정되어 볼 수 있도록 하세요.

- [x] pc, tablet 사이즈의 이미지는 고정값을 사용하고, mobile 사이즈는 좌우 여백 32px을 제외한 이미지 영역이 꽉 찰 수 있도록 해주세요. 이때 가로가 커지는 비율에 맞춰 세로도 커지면 됩니다.
- [x] PC 사이즈에서 기기의 width가
1920px 이상이면 내부에 있는 요소의 위치는 landing/pc 와 동일한 간격을 유지하며 가운데 정렬해야 합니다.
- [x] PC 사이즈에서 기기의 width가 1920px 보다 작아질 때, “Linkbrary” 로고의 왼쪽 여백 200px “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소간 거리가 가까워져야 합니다.

- [x] tablet 사이즈에서 기기의 width가 1199px 에서 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 유지하고 좌우 여백이 줄어듭니다. 863px 보다 작아질 때, “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px이 최소 여백을 유지할 수 있도록 “Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지도록 합니다.

- [x] mobile 사이즈에서 기기의 width에 관계없이 전체 좌우 여백이 32px을 유지하도록 하고, 이미지 요소의 경우 좌우 여백 32px을 제외하고 이미지가 꽉 찰 수 있도록 width와 height가 원본의 비율대로 커지도록 합니다.

- [x] mobile 사이즈 width가 커지면, Privacy Policy, FAQ가 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지도록 하세요.

## 추가 요구사항
- [ ] 사용자의 브라우저 font-size가 크고 작아짐에 따라 페이지의 요소간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정 하세요.

- [x] mobile 사이즈에서만 제목, 이미지, 설명의 순서대로 배치해 주세요.<br/><br/>

# 3). 멘토님께 드리는 질문
- 로그인 버튼 같은 경우 글자가 없는 버튼 영역에도 마우스 갖다대면 클릭 가능하게 바뀌는데 링크 추가하기 버튼은 글자부분에 가야 커서 모양이 바뀌는데 이유가 뭘까요?? 제가 봤을 땐 둘 다 똑같이 a태그에 div로 감싸서 작성했는데..
- header_title 클래스 및 h1태그인 '세상의 모든 정보를 ~ 관리해보세요'를 데스크탑과 태블릿, 모바일 디자인에 맞추어 줄바꿈이 되게 하려면 어떻게 해야할까요?? 
- font size가 크고 작아짐에 따라 요소 간격, 크기, font-size 모두 바뀌려면 모든 픽셀을 다 rem으로 계산해서 적어야 하는 건가요?

2023-04-10 07:19 UTC, ghost requested changes
> 로그인 버튼 같은 경우 글자가 없는 버튼 영역에도 마우스 갖다대면 클릭 가능하게 바뀌는데 링크 추가하기 버튼은 글자부분에 가야 커서 모양이 바뀌는데 이유가 뭘까요?? 제가 봤을 땐 둘 다 똑같이 a태그에 div로 감싸서 작성했는데..

이 부분은 [코드리뷰](https://github.com/codeit-bootcamp-frontend/Weekly-Mission/pull/46#discussion_r1161468441)에 남겼습니다!

> header_title 클래스 및 h1태그인 '세상의 모든 정보를 ~ 관리해보세요'를 데스크탑과 태블릿, 모바일 디자인에 맞추어 줄바꿈이 되게 하려면 어떻게 해야할까요??

`<br>` 태그를 활용하는 방향을 고민해 보시면 좋을 거 같습니다! `<br>` 요소에도 CSS를 적용할 수 있습니다.

> font size가 크고 작아짐에 따라 요소 간격, 크기, font-size 모두 바뀌려면 모든 픽셀을 다 rem으로 계산해서 적어야 하는 건가요?
네, 맞습니다.
브라우저 설정에서 폰트 크기를 정할 수 있는데(일반적으로는 16px이 기본 값) 이것이 `<html>` 태그의 기본 `font-size`로 지정돼요. 

`<html>` 태그의 `font-size` === `1rem` 입니다.

rem 단위 계산을 쉽게 하기 위해서 `font-size: 62.5%`를 `html`에다 지정하는 방법을 쓰기도 합니다. 일반적으로 웹 브라우저의 기본 폰트 크기가 16px인데요, 이 값의 62.5%는 10px가 됩니다. 그래서 1rem === 10px 이기 때문에 이 관계를 이용해서 px 크기를 쉽게 rem으로 바꿀 수 있습니다.

이렇게 설정한 상태에서 만약에 사용자가 웹 브라우저 기본 폰트 크기를 32px로 바꾸면, rem 단위로 작성된 값들은 모두 비례해서 두 배로 커지게 됩니다.

[관련 블로그 글: 62.5% font-size trick](https://www.aleksandrhovhannisyan.com/blog/62-5-percent-font-size-trick/#setting-the-root-font-size-to-625percent)

2023-04-14 08:46 UTC, ghost commented
일단 이번 PR은 머지하도록 하겠습니다!

2023-04-14 08:46 UTC, merged

2023-04-15 06:34 UTC, Noahcodeit commented on style.css
> +  font-size: 18px;
여백을 활용하라는게  padding을 이용하라는 말씀이신가요?

2023-04-23 11:23 UTC, Noahcodeit commented on style.css
> +  font-size: 18px;
@cdtkrk  여백을 활용하라는게 padding을 이용하라는 말씀이신가요?